{
    "name": "Report Generator",
    "description": "Custom PDF Report Generator.",
    "summary": """This module will generate custom QWeb Reports.""",
    "installable": True,
    "application": True,
    "depends": ["base", "web", "account", "project", "sale"],
    "license": "LGPL-3",
    "version": "18.0.0.1",
    "data": [
        "security/ir.model.access.csv",
        "report/report_customer_action.xml",
        "wizard/report_date_range_actions.xml",
        "report/report_project_timesheet_actions.xml",
        "report/report_project_timesheet_template.xml",
        "wizard/report_date_range_menus.xml",
        "report/report_customer_template.xml",
        "views/res_partner_menus.xml",
        "report/report_saleorder_template.xml",
        "wizard/report_date_range_views.xml",
    ],
}
